### ISSUE TITLE
Any plan to porting Navigator to flutter?

### ISSUE THREAD

**Issue by winterdl** [Mantano/mp_readium#1]
I’ve just tested display an epub using flutter webview, but it has some issues about rendering and performance. Do you have any plans about porting Navigator to Flutter?

**Comment by winterdl** [comment]
Thank you for your informations, I've tested the flutter webview, for now the flutter webview could not created from offscreen, when changing chapter (resource), the reader view takes time to load and rendering, I could not preload the webview, and and got some issues about gesture arena when combine webview and pageview.

**Comment by jmgeffroy** [comment]
OK I see. Yes, these are definitely issues addressed by our navigator (any other navigators from the original Readium project).

**Comment by jmgeffroy** [comment]
Wow, besides the issues, that's already a good start! Did you already integrate Readium CSS for style customization? You seem pretty familiar with Readium, are you?

**Comment by winterdl** [comment]
Yes, I did, I integrated with Readium css and js, with my custom css, js. I'm researching epub reading solution for my next project, I've read the Readium code but not good understood yet. I prefer flutter only solution, but because of deadline, maybe I will chosing Readium integrating by Platform Channel, my flutter app will call platform channel and using kotlin and swift. I will comback to flutter solution when have time.

**Comment by jmgeffroy** [comment]
I understand. If I correctly remember, I think another Readium Foundation member organization will release soon an open source integration based on platform channels. If you are also a member, you could contact them. They are present in our Slack discussion channels dedicated to building a Flutter Readium (currently "Mantano MP Reader" is only a Mantano initiative to boost this idea).

**Comment by mohsin2217A** [comment]
> Thank you for your informations, but I'm not a member of the organization, if you have any links about the project, please let me know, thank you so much. Before Readium, I’ve tried epubjs with flutter for a lightweight epub reader, it works well for epub less than 2Mb. About Readium, I've finished android plugin part, based on hard working of [JideGuru](https://github.com/JideGuru/epub_viewer/tree/readium-android), i will contribute back when finish the test, and implementing ios plugin part.
> 
> The clip so lag because of emulator, but it runs smooth on real device.
> 
>  android.mp4

Hello,
Can you please share the source code of this?
Have you achieved highlight / annotations and comments on Epub Reader?
